import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import RQProvider from "@/context/RQProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"
        />
      </header>
      <body>
        <RQProvider>
          <Header />
          {children}
        </RQProvider>

        <script src="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.js"></script>
      </body>
    </html>
  );
}
