import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import RQProvider from "@/context/RQProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQProvider>
          <Header />
          {children}
        </RQProvider>
      </body>
    </html>
  );
}
